[params]
fonts_engine = "inkscape"
fragments = true

[fragments.step1]
excluded_layers = ["terminal", "export-logo"]

[fragments.step2]
excluded_layers = ["export-logo"]

[fragments.step3]
excluded_layers = []
